site_name: 《离散数学》课程 Q&A

theme:
  name: material
  custom_dir: overrides
  language: zh
  features:
    - content.code.copy
    - content.code.select
    - navigation.path
  palette: 
    # Palette toggle for light mode
    - scheme: default
      primary: cyan
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: black
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

plugins:
  - git-revision-date-localized:
      enable_creation_date: true
  - search:
      separator: '[\s\u200b\-]'
  - glightbox

extra_javascript: 
  - 'https://cdn.jsdelivr.net/npm/mathjax@2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'

markdown_extensions: 
  - admonition 
  - codehilite: 
      guess_lang: false 
      linenums: true 
  - footnotes 
  - def_list 
  - toc: 
      permalink: true 
  - pymdownx.arithmatex 
  - pymdownx.caret 
  - pymdownx.critic 
  - pymdownx.details 
  - pymdownx.inlinehilite 
  - pymdownx.magiclink 
  - pymdownx.mark 
  - pymdownx.smartsymbols 
  - pymdownx.tasklist: 
      custom_checkbox: true 
  - pymdownx.tilde 
  - meta 
  - pymdownx.highlight: 
      linenums: true 
  - pymdownx.keys 
  - pymdownx.snippets 
  - pymdownx.progressbar 
  - pymdownx.superfences 
  - pymdownx.tabbed: 
      alternate_style: true  
  - pymdownx.superfences: 
      custom_fences: 
      - name: math 
        class: arithmatex 
        format: !!python/name:pymdownx.arithmatex.fence_mathjax_format

nav:
  - dm-qa-base.md
  - dm-qa-main.md